apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: infrastructure
spec:
  destination:
    namespace: argocd
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  project: argocd
  source:
    repoURL: git@github.com:daryaolejnik/infra-argocd.git
    targetRevision: HEAD
    path: infrastructure
    directory:
      recurse: true
