---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
  annotations:
    # This is the key annotation to create NLB instead of Classic LB
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-name: "doliinyk-app-nlb"

spec:
  destination:
    namespace: infrastructure
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  project: infrastructure
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.7.1
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
