---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
  annotations:

spec:
  destination:
    namespace: infrastructure
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  project: infrastructure
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.7.1
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
              service.beta.kubernetes.io/aws-load-balancer-name: "doliinyk-app-nlb"
              service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-north-1:102205351130:certificate/26d4a81f-0696-4994-8363-8d2be24799db
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
            type: LoadBalancer
