---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
  annotations:

spec:
  destination:
    namespace: infrastructure
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  project: infrastructure
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.7.1
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
