---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
  annotations:

spec:
  destination:
    namespace: infrastructure
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  project: infrastructure
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.7.1
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          ingressClass: nginx
          service:
            enabled: true
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "external"
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
              service.beta.kubernetes.io/aws-load-balancer-name: "doliinyk-app-nlb"
              service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-north-1:102205351130:certificate/1284ff26-b8f4-41c3-af95-a4754df44db2
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'ssl'
              service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
              service.beta.kubernetes.io/aws-load-balancer-internal: false
            type: LoadBalancer
            enableHttp: false
            # targetPorts:
            #   https: https
          config:
            use-proxy-protocol: "true"
            real-ip-header: "proxy_protocol"
            use-forwarded-headers: "true"
