---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
  annotations:

spec:
  destination:
    namespace: infrastructure
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  project: infrastructure
  source:
    repoURL: git@github.com:daryaolejnik/argocd.git
    targetRevision: HEAD
    path: infrastructure/ingress-nginx
